### ISSUE TITLE
Second installation is aborted because of verison check after first installation failed

### ISSUE THREAD

**Issue by qiaojingx** [cuiyanx/WMLP#3]
Try to run WMLP. A installation issue occurs, this issue may cause that test target is not the newest version.
Reproduce steps:
1. git clone https://github.com/cuiyanx/WMLP
2. cd WMLP
3. npm install 
4. npm start (i forgot to change password in JSON)
Then first installation failed because of incorrect password.
5. Change password then repeat step1-4.
6. The second installation is aborted because the package is judged as not the newest version.
Actually: The newest version is not installed successfully due to incorrect password in first installation.

**Comment by cuiyanx** [comment]
Thank for your attention.
I will fixed by #2
